---
- name: Add stable chart repo
  shell: helm repo add projectcalico https://docs.tigera.io/calico/charts
    
- name: Calico Install
  shell: helm install calico projectcalico/tigera-operator --version v3.27.0 --namespace tigera-operator --create-namespace