---
- name: Add repo kubernetes
  when: ansible_facts['os_family'] == "RedHat"
  yum_repository:
    name: kubernetes
    description: 'Base programs for k8s'
    baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
    gpgcheck: yes
    gpgkey: 
      - 'https://packages.cloud.google.com/yum/doc/yum-key.gpg'
      - 'https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'



- name: Install Kubernetes packages
  yum:
    name:
      - containerd.io
      - kubeadm-1.27.5
      - kubectl-1.27.5
      - kubelet-1.27.5
    state: present
  notify: started kubelet

- name: Enable kubelet
  service: 
    name: kubelet 
    enabled: yes 

- name: Copy kubeadm-config
  copy: 
    src: kubeadm-config.yaml
    dest: /etc/kubernetes/kubeadm-config.yaml
    owner: root
    mode: 0644
  
- name: Copy .bashrc
  copy: 
    src: .bashrc
    dest: /home/{{user}}/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0664

...
