---
- name: Add repo kubernetes
  when: ansible_facts['os_family'] == "RedHat"
  yum_repository:
    name: kubernetes
    description: 'Base programs for k8s'
    baseurl: "{{ k8s_yum_repository }}"
    gpgcheck: yes
    gpgkey: "{{ k8s_gpgkey }}"

- name: Install Kubernetes packages
  yum:
    name:
      - containerd.io
      - kubeadm
      - kubectl
      - kubelet
    state: present
  notify: started kubelet

- name: Enable kubelet
  service: 
    name: kubelet 
    enabled: yes 

- name: Copy kubeadm-config
  copy: 
    src: kubeadm-config.yaml
    dest: /etc/kubernetes/kubeadm-config.yaml
    owner: root
    mode: 0644
  

...
