---
- name: Download Helm 
  get_url:
    url: "{{ HELM_URL }}"
    dest: "/tmp/{{ HELM_URL | basename }}"
- name: Extract archive
  unarchive:
    src: "/tmp/{{ HELM_URL | basename }}"
    dest: "/tmp/"
    remote_src: yes
- name: Copy Helm to /usr/local/bin/
  copy:
    src: "/tmp/linux-amd64/helm"
    dest: "/usr/local/bin/"    
    remote_src: yes
    mode: 0777
- name: Helm complition bash
  shell: helm completion bash > /etc/bash_completion.d/helm    