---
- name: Add user 
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/bash
    groups: wheel
    append: yes
    password: "{{ password | password_hash('sha512') }}"
    state: present  
    update_password: on_create

# - name: Set authorized key 
#   ansible.posix.authorized_key:
#     user: 
#     state: present
#     key: "{{ lookup('file', '~/.ssh/fozzy.pub') }}"    