---
- name: Create token for join
  shell: kubeadm token create --print-join-command
  register: join_command
  when: inventory_hostname == 'k8s-m1'

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
  when: inventory_hostname == 'k8s-m1'
- name: Copy the join command to server location
  copy: 
    src: join-command  
    dest: /tmp/join-command.sh 
    mode: 0777

- name: Join the node to cluster
  shell: sh /tmp/join-command.sh
  when: "'nodes' in group_names"
