

# Rhel Alfa repository
k8s_yum_repository: "https://pkgs.k8s.io/core:/stable:/v1.28/rpm/"
k8s_yum_ignore_key_errors: false
k8s_gpgkey: "https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key"

user: ""

k8s_pod_network:
  # Calico CNI.
  cni: 'calico'
  cidr: '192.168.0.0/16'
  
  # Flannel CNI.
  # cni: 'flannel'
  # cidr: '10.244.0.0/16'
  
# Calico config file.
k8s_calico_manifest_file: "https://projectcalico.docs.tigera.io/manifests/calico.yaml"
