- hosts: all
  become: yes
  tasks:
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/home/astorf/.ssh/id_rsa.pub') }}"
