---
- name: Nodes configuration 
  hosts: all
  become: true
  remote_user: root
  roles:
    - set-hostname
    - set-time-zone
    - set-hosts-etc
    - install-tools
    - install-docker
    - new-useradd
    - install-helm
  tags:
    - node-config

- name: install kubernetes
  hosts: k8s_cluster
  become: true
  remote_user: root
  roles:
    - install-kubernetes
  tags:
    - install-kube

- name: Worker init
  hosts: k8s_cluster
  become: true
  remote_user: root
  roles:
    - worker-init
  tags:
    - worker-init

- name: install Helm charts
  hosts: k8s-m1
  become: true
  remote_user: root
  roles:
    - helm-charts
  tags:
    - install-helm-charts    




# - name: install haproxy
#   hosts: control_plane
#   become: true
#   remote_user: root
#   roles:
#     - install-ha-keepalived
#   tags:
#     - install-haproxy


# - name: init control plane
#   hosts: all
#   become: true
#   remote_user: root
#   roles:
#     - k8s-init
#   tags:
#     - k8s-init
    
...   