---
- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
   
- name: Erase containers-common 
  yum:
    name:
      - containers-common 
      - podman
      - buildah
    state: absent


- name: install docker and it's dependencies
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin 
      - containerd.io
    state: present

- name: start and enable docker daemon
  service:
    name: docker
    state: started
    enabled: yes

# - name: Check docker-compose file already exists.
#   stat: path=/usr/bin/docker-compose
#   register: docker_compose_file

# - name: Install Docker-compose
#   shell: curl -L "https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose && ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
#   become: true
#   when: not docker_compose_file.stat.exists    

# - name: Add the current user to docker group
#   user: name=ubuntu append=yes groups=docker  